services:
 db:
   build:
     context: ./postgresql
   container_name: retro-hunter_db
   restart: unless-stopped
   env_file:
     - .env
   environment:
     POSTGRES_USER: ${POSTGRES_USER}
     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
     POSTGRES_DB: ${POSTGRES_DB}
   volumes:
     - pg_data:/var/lib/postgresql/data
   ports:
     - "5432:5432"
   networks:
     - retro-net

 streamlit:
   build: ./streamlit
   container_name: retro-hunter-dashboard
   ports:
     - "8501:8501"
   volumes:
     - ./certs:/app/certs
   env_file:
     - .env
   networks:
     - retro-net
   restart: unless-stopped

 mcp-server:
   build:
     context: ./mcp_server
   container_name: retro-hunter-mcp
   ports:
     - "8000:8000"
   volumes:
     - ./certs:/app/certs
   env_file:
     - .env
   depends_on:
     - db
   networks:
     - retro-net
   restart: unless-stopped

networks:
 retro-net:

volumes:
 pg_data:
